---
apiVersion: v1
kind: ConfigMap
metadata:
  name: another-ldap
  namespace: another
data:
  LDAP_ENDPOINT: "ldap://my-openldap-stack-ha.default.svc.cluster.local"
  LDAP_MANAGER_DN_USERNAME: "CN=admin,DC=example,DC=org"
  LDAP_BIND_DN: "UID={username}.OU=users,DC=example,DC=org"
  LDAP_SEARCH_BASE: "DC=example,DC=org"
  LDAP_SEARCH_FILTER: "(sAMAccountName={username})"
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "JSON"
  BRUTE_FORCE_PROTECTION: "False"
  BRUTE_FORCE_EXPIRATION: "5"
  BRUTE_FORCE_FAILURES: "3"
  COOKIE_DOMAIN: ""
  METADATA_TITLE: "Another LDAP"
  METADATA_DESCRIPTION: ""
  METADATA_FOOTER: "Powered by Another LDAP"
  PERMANENT_SESSION_LIFETIME: "7"